---
http_interactions:
- request:
    method: get
    uri: https://qb.sbfinance.intuit.com/v3/company/835973000/query?query=select%20*%20from%20Account%20where%20Name%20=%20'Sales%20of%20Product%20Income'%20STARTPOSITION%201%20MAXRESULTS%2020
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/xml
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - OAuth gem v0.4.7
      Authorization:
      - OAuth oauth_consumer_key="qyprdcG20NCyjy5jd7tKal9ivdOcbH", oauth_nonce="rxlp5YHB1gLRytIaEo8eOJrxXbfsMj2wUUyeURLo",
        oauth_signature="tyepYns9YFKkNhY3g%2BdJ3t9GZPY%3D", oauth_signature_method="HMAC-SHA1",
        oauth_timestamp="1387291199", oauth_token="qyprdhjEBfA2BI8sD7fWVPH4wL9esaKrYeWLosiPBir3pa5j",
        oauth_version="1.0"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 17 Dec 2013 14:40:00 GMT
      Server:
      - Apache/2.2.22 (Unix)
      Qbo-Version:
      - '68.147'
      Cache-Control:
      - max-age=0, no-cache, no-store, must-revalidate, private
      Expires:
      - '0'
      Intuit-Tid:
      - 82f7b073-073d-42a6-a1d0-c60603a4a786
      Via:
      - 1.1 ipp-gateway-ap01
      Content-Length:
      - '455'
      Connection:
      - close
      Content-Type:
      - application/xml;charset=UTF-8
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse
        xmlns="http://schema.intuit.com/finance/v3" time="2013-12-17T06:40:00.924-08:00"><QueryResponse
        startPosition="1" maxResults="1"><Account domain="QBO" sparse="false"><Id>4</Id><SyncToken>0</SyncToken><MetaData><CreateTime>2013-11-15T12:43:10-08:00</CreateTime><LastUpdatedTime>2013-11-15T12:43:10-08:00</LastUpdatedTime></MetaData><Name>Sales
        of Product Income</Name><SubAccount>false</SubAccount><FullyQualifiedName>Sales
        of Product Income</FullyQualifiedName><Active>true</Active><Classification>Revenue</Classification><AccountType>Income</AccountType><AccountSubType>SalesOfProductIncome</AccountSubType><CurrentBalance>0</CurrentBalance><CurrentBalanceWithSubAccounts>0</CurrentBalanceWithSubAccounts><CurrencyRef
        name="United States Dollar">USD</CurrencyRef></Account></QueryResponse></IntuitResponse>
    http_version: 
  recorded_at: Tue, 17 Dec 2013 14:40:01 GMT
- request:
    method: get
    uri: https://qb.sbfinance.intuit.com/v3/company/835973000/query?query=select%20*%20from%20Account%20where%20Name%20=%20'Inventory%20Asset'%20STARTPOSITION%201%20MAXRESULTS%2020
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/xml
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - OAuth gem v0.4.7
      Authorization:
      - OAuth oauth_consumer_key="qyprdcG20NCyjy5jd7tKal9ivdOcbH", oauth_nonce="ppDzKxVVP6emm1J0uAu1lAMOXABGH0x31RJQapPORA",
        oauth_signature="rJp9LK1lcyLf1rGLbY4s9XN17pw%3D", oauth_signature_method="HMAC-SHA1",
        oauth_timestamp="1387291201", oauth_token="qyprdhjEBfA2BI8sD7fWVPH4wL9esaKrYeWLosiPBir3pa5j",
        oauth_version="1.0"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 17 Dec 2013 14:40:02 GMT
      Server:
      - Apache/2.2.22 (Unix)
      Qbo-Version:
      - '68.147'
      Cache-Control:
      - max-age=0, no-cache, no-store, must-revalidate, private
      Expires:
      - '0'
      Intuit-Tid:
      - ced8d9a0-c3e5-4ead-a203-596dfa1822a1
      Via:
      - 1.1 ipp-gateway-ap01
      Content-Length:
      - '460'
      Connection:
      - close
      Content-Type:
      - application/xml;charset=UTF-8
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse
        xmlns="http://schema.intuit.com/finance/v3" time="2013-12-17T06:40:02.253-08:00"><QueryResponse
        startPosition="1" maxResults="1"><Account domain="QBO" sparse="false"><Id>6</Id><SyncToken>0</SyncToken><MetaData><CreateTime>2013-11-15T12:43:11-08:00</CreateTime><LastUpdatedTime>2013-11-27T10:55:44-08:00</LastUpdatedTime></MetaData><Name>Inventory
        Asset</Name><SubAccount>false</SubAccount><FullyQualifiedName>Inventory Asset</FullyQualifiedName><Active>true</Active><Classification>Asset</Classification><AccountType>Other
        Current Asset</AccountType><AccountSubType>Inventory</AccountSubType><CurrentBalance>12.00</CurrentBalance><CurrentBalanceWithSubAccounts>12.00</CurrentBalanceWithSubAccounts><CurrencyRef
        name="United States Dollar">USD</CurrencyRef></Account></QueryResponse></IntuitResponse>
    http_version: 
  recorded_at: Tue, 17 Dec 2013 14:40:02 GMT
- request:
    method: get
    uri: https://qb.sbfinance.intuit.com/v3/company/835973000/query?query=select%20*%20from%20Account%20where%20Name%20=%20'Cost%20of%20Goods%20Sold'%20STARTPOSITION%201%20MAXRESULTS%2020
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/xml
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - OAuth gem v0.4.7
      Authorization:
      - OAuth oauth_consumer_key="qyprdcG20NCyjy5jd7tKal9ivdOcbH", oauth_nonce="EFyF94ZDvUOo6CE9uO4Do2Sx2RVvaXO02AcQ0DBvU",
        oauth_signature="d2j2lP1V3ykzi4XRhbi3S51tuyM%3D", oauth_signature_method="HMAC-SHA1",
        oauth_timestamp="1387291202", oauth_token="qyprdhjEBfA2BI8sD7fWVPH4wL9esaKrYeWLosiPBir3pa5j",
        oauth_version="1.0"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 17 Dec 2013 14:40:03 GMT
      Server:
      - Apache/2.2.22 (Unix)
      Qbo-Version:
      - '68.147'
      Cache-Control:
      - max-age=0, no-cache, no-store, must-revalidate, private
      Expires:
      - '0'
      Intuit-Tid:
      - 3bdf41e4-f31e-4e79-9c1f-9862315bfb8a
      Via:
      - 1.1 ipp-gateway-ap05
      Content-Length:
      - '461'
      Connection:
      - close
      Content-Type:
      - application/xml;charset=UTF-8
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse
        xmlns="http://schema.intuit.com/finance/v3" time="2013-12-17T06:40:03.406-08:00"><QueryResponse
        startPosition="1" maxResults="1"><Account domain="QBO" sparse="false"><Id>5</Id><SyncToken>0</SyncToken><MetaData><CreateTime>2013-11-15T12:43:11-08:00</CreateTime><LastUpdatedTime>2013-11-15T12:43:11-08:00</LastUpdatedTime></MetaData><Name>Cost
        of Goods Sold</Name><SubAccount>false</SubAccount><FullyQualifiedName>Cost
        of Goods Sold</FullyQualifiedName><Active>true</Active><Classification>Expense</Classification><AccountType>Cost
        of Goods Sold</AccountType><AccountSubType>SuppliesMaterialsCogs</AccountSubType><CurrentBalance>0</CurrentBalance><CurrentBalanceWithSubAccounts>0</CurrentBalanceWithSubAccounts><CurrencyRef
        name="United States Dollar">USD</CurrencyRef></Account></QueryResponse></IntuitResponse>
    http_version: 
  recorded_at: Tue, 17 Dec 2013 14:40:03 GMT
- request:
    method: get
    uri: https://qb.sbfinance.intuit.com/v3/company/835973000/query?query=select%20*%20from%20Item%20where%20Name%20=%20'nine-inch-nails-cd'%20STARTPOSITION%201%20MAXRESULTS%2020
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/xml
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - OAuth gem v0.4.7
      Authorization:
      - OAuth oauth_consumer_key="qyprdcG20NCyjy5jd7tKal9ivdOcbH", oauth_nonce="4amdPkfWW02RDRXcBw8I9QXtrw1CS2ymjB9RxaTv6A",
        oauth_signature="sImNK4g3qIdRchLtLOcv9ZJCfDs%3D", oauth_signature_method="HMAC-SHA1",
        oauth_timestamp="1387291203", oauth_token="qyprdhjEBfA2BI8sD7fWVPH4wL9esaKrYeWLosiPBir3pa5j",
        oauth_version="1.0"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 17 Dec 2013 14:40:04 GMT
      Server:
      - Apache/2.2.22 (Unix)
      Qbo-Version:
      - '68.147'
      Cache-Control:
      - max-age=0, no-cache, no-store, must-revalidate, private
      Expires:
      - '0'
      Intuit-Tid:
      - 5b3f1742-9dcb-45c8-8dc4-0d0bcc6706f7
      Via:
      - 1.1 ipp-gateway-ap03
      Content-Length:
      - '167'
      Connection:
      - close
      Content-Type:
      - application/xml;charset=UTF-8
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse
        xmlns="http://schema.intuit.com/finance/v3" time="2013-12-17T06:40:04.419-08:00"><QueryResponse/></IntuitResponse>
    http_version: 
  recorded_at: Tue, 17 Dec 2013 14:40:04 GMT
- request:
    method: post
    uri: https://qb.sbfinance.intuit.com/v3/company/835973000/item
    body:
      encoding: UTF-8
      string: |-
        <?xml version="1.0" encoding="utf-8"?>
        <Item xmlns="http://schema.intuit.com/finance/v3" sparse="false">
        <Name>nine-inch-nails-cd</Name>
        <Description>Some description text for the product.</Description>
        <UnitPrice>31</UnitPrice>
        <Type>Inventory</Type>
        <AssetAccountRef>6</AssetAccountRef>
        <IncomeAccountRef>4</IncomeAccountRef>
        <ExpenseAccountRef>5</ExpenseAccountRef>
        </Item>
    headers:
      Content-Type:
      - application/xml
      Accept:
      - application/xml
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - OAuth gem v0.4.7
      Content-Length:
      - '376'
      Authorization:
      - OAuth oauth_body_hash="3wGYz8yBqEoR42xBHsZMw01fKUQ%3D", oauth_consumer_key="qyprdcG20NCyjy5jd7tKal9ivdOcbH",
        oauth_nonce="ClReSPABDpOqDcozSfF4QMQNcR4xFQi5aSTtc3puzQ", oauth_signature="fWBevIpvK3gJkTsQqE9C%2FLvUW1E%3D",
        oauth_signature_method="HMAC-SHA1", oauth_timestamp="1387291204", oauth_token="qyprdhjEBfA2BI8sD7fWVPH4wL9esaKrYeWLosiPBir3pa5j",
        oauth_version="1.0"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 17 Dec 2013 14:40:05 GMT
      Server:
      - Apache/2.2.22 (Unix)
      Qbo-Version:
      - '68.147'
      Cache-Control:
      - max-age=0, no-cache, no-store, must-revalidate, private
      Expires:
      - '0'
      Intuit-Tid:
      - 419573c5-adc0-49bd-a2f8-dc25d9aae30a
      Via:
      - 1.1 ipp-gateway-ap02
      Content-Length:
      - '438'
      Connection:
      - close
      Content-Type:
      - application/xml;charset=UTF-8
    body:
      encoding: UTF-8
      string: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse
        xmlns="http://schema.intuit.com/finance/v3" time="2013-12-17T06:40:05.764-08:00"><Item
        domain="QBO" sparse="false"><Id>41</Id><SyncToken>0</SyncToken><MetaData><CreateTime>2013-12-17T06:40:05-08:00</CreateTime><LastUpdatedTime>2013-12-17T06:40:05-08:00</LastUpdatedTime></MetaData><Name>nine-inch-nails-cd</Name><Description>Some
        description text for the product.</Description><Active>true</Active><Taxable>false</Taxable><UnitPrice>31</UnitPrice><Type>Service</Type><IncomeAccountRef
        name="Sales of Product Income">4</IncomeAccountRef><PurchaseCost>0</PurchaseCost><ExpenseAccountRef
        name="Cost of Goods Sold">5</ExpenseAccountRef><TrackQtyOnHand>false</TrackQtyOnHand></Item></IntuitResponse>
    http_version: 
  recorded_at: Tue, 17 Dec 2013 14:40:06 GMT
recorded_with: VCR 2.4.0
